FROM node:18 as development

USER node

WORKDIR /node

COPY --chown=node:node package*.json .

RUN npm install

COPY --chown=node:node . .

RUN npx prisma generate

EXPOSE 8081

CMD ["npm", "run", "start:compose"]